# Generated by Django 4.1.7 on 2023-03-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usermaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.BigIntegerField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serviceprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=150)),
                ('equipment', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(upload_to='app/img/candidate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Hotelmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('ownerphone', models.CharField(max_length=50)),
                ('hotelcontact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('taluka', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=150)),
                ('hotelname', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(upload_to='app/img/candidate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=150)),
                ('crop', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(upload_to='app/img/candidate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster')),
            ],
        ),
    ]
