# Generated by Django 4.1.7 on 2023-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
