# Generated by Django 4.1.7 on 2023-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0002_news_is_created_news_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.CharField(max_length=500),
        ),
    ]
