# Generated by Django 4.1.7 on 2023-03-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0006_remove_schemes_date_alter_schemes_publishdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('role', models.BigIntegerField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
