# Generated by Django 4.1.7 on 2023-03-28 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0008_admin_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster'),
        ),
    ]
