# Generated by Django 4.1.7 on 2023-03-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0010_adminuser_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='role',
            field=models.BigIntegerField(),
        ),
    ]
