# Generated by Django 4.1.7 on 2023-03-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0011_alter_adminuser_role_alter_usermaster_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=8)),
                ('is_created', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
