# Generated by Django 4.1.7 on 2023-03-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0013_alter_user_admin_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_admin',
            name='role',
            field=models.BigIntegerField(default=1),
        ),
    ]
