# Generated by Django 4.1.7 on 2023-03-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0014_user_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('productprice', models.IntegerField()),
                ('quality', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='app/img/product')),
            ],
        ),
    ]
