# Generated by Django 4.1.7 on 2023-04-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0015_productdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='hotelmanager',
            name='ownerphone',
        ),
        migrations.RemoveField(
            model_name='hotelmanager',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='profile_pic',
        ),
    ]
