# Generated by Django 4.1.7 on 2023-04-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0017_farmer_status_hotelmanager_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelmanager',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
