# Generated by Django 4.1.7 on 2023-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0018_alter_farmer_status_alter_hotelmanager_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='approval',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
