# Generated by Django 4.1.7 on 2023-04-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0019_usermaster_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesthotelmanager',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='requestserviceprovider',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='requestFarmer',
        ),
        migrations.DeleteModel(
            name='requestHotelmanager',
        ),
        migrations.DeleteModel(
            name='requestServiceProvider',
        ),
    ]
