# Generated by Django 4.1.7 on 2023-04-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0020_remove_requesthotelmanager_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=150)),
                ('crop', models.CharField(max_length=150)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster')),
            ],
        ),
    ]
