# Generated by Django 4.1.7 on 2023-04-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0021_requestfarmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='hotelmanager',
            name='status',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='status',
        ),
    ]
