# Generated by Django 4.1.7 on 2023-04-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0023_requestserviceprovider_requesthotelmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='firstname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='freshness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='lastname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='requestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('productname', models.CharField(max_length=20)),
                ('productprice', models.IntegerField()),
                ('quality', models.CharField(max_length=15)),
                ('freshness', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(upload_to='app/img/product')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.productdetails')),
            ],
        ),
    ]
