# Generated by Django 4.1.7 on 2023-04-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0024_productdetails_date_productdetails_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestproduct',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster'),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster'),
        ),
    ]
