# Generated by Django 4.1.7 on 2023-04-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0025_remove_requestproduct_product_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requestProduct',
            new_name='Request_Product',
        ),
    ]
