# Generated by Django 4.1.7 on 2023-04-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0026_rename_requestproduct_request_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='photo',
            field=models.ImageField(upload_to='img/product'),
        ),
        migrations.AlterField(
            model_name='request_product',
            name='photo',
            field=models.ImageField(upload_to='img/product'),
        ),
        migrations.CreateModel(
            name='Service_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('service', models.CharField(max_length=20)),
                ('rent', models.IntegerField()),
                ('years', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(upload_to='img/service')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='requestHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('hotelname', models.CharField(max_length=25)),
                ('contact', models.IntegerField()),
                ('requirement', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(upload_to='img/hotel')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Request_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('service', models.CharField(max_length=20)),
                ('rent', models.IntegerField()),
                ('years', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(upload_to='img/service')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('hotelname', models.CharField(max_length=25)),
                ('contact', models.IntegerField()),
                ('requirement', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(upload_to='img/hotel')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster')),
            ],
        ),
    ]
