# Generated by Django 4.1.7 on 2023-04-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0027_alter_productdetails_photo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requestHotel',
            new_name='Request_Hotel',
        ),
    ]
