# Generated by Django 4.1.7 on 2023-04-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0028_rename_requesthotel_request_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_hotel',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='request_product',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='request_service',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
