# Generated by Django 4.1.7 on 2023-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0029_request_hotel_status_request_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='approval',
        ),
        migrations.AddField(
            model_name='requestfarmer',
            name='approval',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
