# Generated by Django 4.1.7 on 2023-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0030_remove_usermaster_approval_requestfarmer_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthotelmanager',
            name='approval',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='requestserviceprovider',
            name='approval',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
