# Generated by Django 4.1.7 on 2023-04-03 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0031_requesthotelmanager_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('productname', models.CharField(max_length=20)),
                ('productprice', models.IntegerField()),
                ('quality', models.CharField(max_length=15)),
                ('freshness', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(upload_to='img/product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sindhugrow.usermaster')),
            ],
        ),
    ]
