# Generated by Django 4.1.7 on 2023-04-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0032_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetails',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/hotel'),
        ),
        migrations.AlterField(
            model_name='request_hotel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/hotel'),
        ),
    ]
