# Generated by Django 4.1.7 on 2023-04-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0033_alter_hoteldetails_photo_alter_request_hotel_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_service',
            old_name='photo',
            new_name='image',
        ),
    ]
