# Generated by Django 4.1.7 on 2023-04-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0035_rename_photo_hoteldetails_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_hotel',
            old_name='photo',
            new_name='image',
        ),
    ]
