# Generated by Django 4.1.7 on 2023-04-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0036_rename_photo_request_hotel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='is_verified',
        ),
    ]
