# Generated by Django 4.1.7 on 2023-05-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sindhugrow', '0038_remove_usermaster_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
